api_platform:
    title: BileMo API
    version: 1.0.0
    show_webby: false
    enable_swagger_ui: true
    enable_re_doc: true

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        pagination_items_per_page: 20
        pagination_maximum_items_per_page: 20
        stateless: true
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
            invalidation:
                xkey:
                    glue: ', '
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    http_cache:
      # To make all responses public by default.
      public: ~

      invalidation:
        # To enable the tags-based cache invalidation system.
        enabled: false

        # URLs of the Varnish servers to purge using cache tags when a resource is updated.
        varnish_urls: [ ]

        # To pass options to the client charged with the request.
        request_options: [ ]

        # Use another service as the purger for example "api_platform.http_cache.purger.varnish.xkey"
        purger: 'api_platform.http_cache.purger.varnish.ban'

